project:
  type: book
  output-dir: docs

book:
  title: "Tayyip Sinan Ocaktan's Progress Journal"
  repo-url: https://github.com/pjournal/mef06-ocaktans
  chapters:
    - index.qmd
    - assignment1.qmd
    - In-class assignment.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

